-- =========================================================
-- Bar 185 PostgreSQL Database Schema
-- =========================================================

BEGIN;

-- =========================================================
-- 1. ENUM TYPES
-- =========================================================

CREATE TYPE user_account_status AS ENUM (
  'active',
  'disabled',
  'removed'
);

CREATE TYPE auth_provider_type AS ENUM (
  'google',
  'mobile_otp'
);

CREATE TYPE staff_account_status AS ENUM (
  'pending',
  'approved',
  'disabled',
  'removed'
);

CREATE TYPE staff_access_action_type AS ENUM (
  'account_created',
  'account_approved',
  'account_disabled',
  'account_removed',
  'account_restored',
  'role_assigned',
  'role_removed'
);

CREATE TYPE menu_item_status AS ENUM (
  'draft',
  'active',
  'unavailable',
  'archived'
);

CREATE TYPE event_status AS ENUM (
  'draft',
  'published',
  'cancelled',
  'completed',
  'archived'
);

CREATE TYPE venue_table_status AS ENUM (
  'active',
  'unavailable',
  'retired'
);

CREATE TYPE booking_type AS ENUM (
  'standard',
  'large_group'
);

CREATE TYPE booking_status AS ENUM (
  'pending',
  'confirmed',
  'declined',
  'cancelled',
  'completed',
  'no_show'
);

CREATE TYPE enquiry_status AS ENUM (
  'new',
  'acknowledged',
  'in_review',
  'contacted',
  'quoted',
  'closed',
  'declined'
);

CREATE TYPE notification_type AS ENUM (
  'booking_confirmation',
  'large_group_acknowledgement',
  'large_group_staff_alert',
  'event_enquiry_acknowledgement',
  'event_enquiry_staff_alert',
  'staff_access_alert'
);

CREATE TYPE notification_channel AS ENUM (
  'email',
  'sms'
);

CREATE TYPE notification_status AS ENUM (
  'pending',
  'queued',
  'sending',
  'sent',
  'failed',
  'cancelled'
);

CREATE TYPE idempotency_status AS ENUM (
  'processing',
  'completed',
  'failed'
);


-- =========================================================
-- 2. IDENTITY AND ACCESS
-- =========================================================

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name VARCHAR(120) NOT NULL,
  email VARCHAR(255) UNIQUE,
  phone_e164 VARCHAR(30) UNIQUE,
  status user_account_status NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE auth_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  provider_type auth_provider_type NOT NULL,
  provider_subject VARCHAR(255) NOT NULL,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_auth_identity_user
    FOREIGN KEY (user_id)
    REFERENCES users(id),

  CONSTRAINT uq_auth_provider_subject
    UNIQUE (provider_type, provider_subject),

  CONSTRAINT uq_user_provider
    UNIQUE (user_id, provider_type)
);


CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_code VARCHAR(50) NOT NULL UNIQUE,
  role_name VARCHAR(100) NOT NULL,
  description TEXT
);


CREATE TABLE user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  assigned_by_user_id BIGINT,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_user_role_user
    FOREIGN KEY (user_id)
    REFERENCES users(id),

  CONSTRAINT fk_user_role_role
    FOREIGN KEY (role_id)
    REFERENCES roles(id),

  CONSTRAINT fk_user_role_assigned_by
    FOREIGN KEY (assigned_by_user_id)
    REFERENCES users(id),

  CONSTRAINT uq_user_role
    UNIQUE (user_id, role_id)
);


CREATE TABLE staff_accounts (
  user_id BIGINT PRIMARY KEY,
  staff_reference VARCHAR(64) NOT NULL UNIQUE,
  status staff_account_status NOT NULL,
  approved_by_user_id BIGINT,
  approved_at TIMESTAMPTZ,
  disabled_at TIMESTAMPTZ,
  removed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_staff_account_user
    FOREIGN KEY (user_id)
    REFERENCES users(id),

  CONSTRAINT fk_staff_account_approved_by
    FOREIGN KEY (approved_by_user_id)
    REFERENCES users(id)
);


CREATE TABLE staff_access_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id BIGINT NOT NULL,
  performed_by_user_id BIGINT,
  action_type staff_access_action_type NOT NULL,
  role_id BIGINT,
  previous_staff_status staff_account_status,
  new_staff_status staff_account_status,
  request_id VARCHAR(64),
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_staff_audit_target_user
    FOREIGN KEY (target_user_id)
    REFERENCES users(id),

  CONSTRAINT fk_staff_audit_performed_by
    FOREIGN KEY (performed_by_user_id)
    REFERENCES users(id),

  CONSTRAINT fk_staff_audit_role
    FOREIGN KEY (role_id)
    REFERENCES roles(id)
);

CREATE INDEX idx_staff_audit_request_id
  ON staff_access_audit_log(request_id);

CREATE INDEX idx_staff_audit_target_user
  ON staff_access_audit_log(target_user_id);

CREATE INDEX idx_staff_audit_performed_by
  ON staff_access_audit_log(performed_by_user_id);

CREATE INDEX idx_staff_audit_created_at
  ON staff_access_audit_log(created_at);


-- =========================================================
-- 3. VENUE CONFIGURATION
-- =========================================================

CREATE TABLE venues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_reference VARCHAR(64) NOT NULL UNIQUE,
  venue_name VARCHAR(150) NOT NULL,
  address_line1 VARCHAR(255) NOT NULL,
  suburb VARCHAR(120) NOT NULL,
  state VARCHAR(80) NOT NULL,
  postcode VARCHAR(20) NOT NULL,
  country VARCHAR(100) NOT NULL,
  public_phone VARCHAR(30),
  public_email VARCHAR(255),
  timezone VARCHAR(100) NOT NULL,
  is_active BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE venue_hours (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  day_of_week INT NOT NULL,
  opens_at TIME,
  closes_at TIME,
  is_closed BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_venue_hours_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT uq_venue_hours_day
    UNIQUE (venue_id, day_of_week)
);


CREATE TABLE venue_public_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  content_key VARCHAR(100) NOT NULL,
  content_value TEXT NOT NULL,
  sort_order INT NOT NULL,
  is_active BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_venue_public_content_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT uq_venue_content_key
    UNIQUE (venue_id, content_key)
);


-- =========================================================
-- 4. MENU AND EVENTS
-- =========================================================

CREATE TABLE menu_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_reference VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  slug VARCHAR(150) NOT NULL UNIQUE,
  description TEXT,
  sort_order INT NOT NULL,
  is_active BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_item_reference VARCHAR(64) NOT NULL UNIQUE,
  category_id BIGINT NOT NULL,
  name VARCHAR(150) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  sku VARCHAR(80) UNIQUE,
  description TEXT,
  price NUMERIC(10,2) NOT NULL,
  status menu_item_status NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_menu_item_category
    FOREIGN KEY (category_id)
    REFERENCES menu_categories(id)
);


CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_reference VARCHAR(64) NOT NULL UNIQUE,
  title VARCHAR(180) NOT NULL,
  slug VARCHAR(200) NOT NULL UNIQUE,
  description TEXT,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ,
  status event_status NOT NULL,
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_event_created_by
    FOREIGN KEY (created_by_user_id)
    REFERENCES users(id)
);


-- =========================================================
-- 5. BOOKING CONFIGURATION
-- =========================================================

CREATE TABLE booking_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  minimum_party_size INT NOT NULL,
  maximum_standard_party_size INT NOT NULL,
  large_group_threshold INT NOT NULL,
  booking_window_days INT NOT NULL,
  slot_interval_minutes INT NOT NULL,
  standard_booking_duration_minutes INT NOT NULL,
  public_instructions TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_booking_rules_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT uq_booking_rules_venue
    UNIQUE (venue_id)
);


CREATE TABLE booking_blackouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  reason VARCHAR(255),
  blocks_public_bookings BOOLEAN NOT NULL,
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_booking_blackout_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT fk_booking_blackout_created_by
    FOREIGN KEY (created_by_user_id)
    REFERENCES users(id)
);

CREATE INDEX idx_booking_blackouts_venue
  ON booking_blackouts(venue_id);

CREATE INDEX idx_booking_blackouts_starts_at
  ON booking_blackouts(starts_at);

CREATE INDEX idx_booking_blackouts_ends_at
  ON booking_blackouts(ends_at);


CREATE TABLE venue_tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  table_code VARCHAR(50) NOT NULL,
  table_name VARCHAR(100) NOT NULL,
  capacity INT NOT NULL,
  status venue_table_status NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_venue_table_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT uq_venue_table_code
    UNIQUE (venue_id, table_code)
);


CREATE TABLE booking_slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  total_capacity INT NOT NULL,
  reserved_capacity INT NOT NULL,
  version_number INT NOT NULL,
  is_open BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_booking_slot_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT uq_booking_slot_time
    UNIQUE (venue_id, starts_at, ends_at)
);


-- =========================================================
-- 6. BOOKINGS AND EVENT ENQUIRIES
-- =========================================================

CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_reference VARCHAR(64) NOT NULL UNIQUE,
  booking_slot_id BIGINT NOT NULL,
  booking_type booking_type NOT NULL,
  status booking_status NOT NULL,
  party_size INT NOT NULL,
  customer_name VARCHAR(150) NOT NULL,
  customer_email VARCHAR(255) NOT NULL,
  customer_phone VARCHAR(30),
  special_requests TEXT,
  reviewed_by_user_id BIGINT,
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_booking_slot
    FOREIGN KEY (booking_slot_id)
    REFERENCES booking_slots(id),

  CONSTRAINT fk_booking_reviewed_by
    FOREIGN KEY (reviewed_by_user_id)
    REFERENCES users(id),

  CONSTRAINT uq_booking_id_slot
    UNIQUE (id, booking_slot_id)
);

CREATE INDEX idx_bookings_slot
  ON bookings(booking_slot_id);

CREATE INDEX idx_bookings_status
  ON bookings(status);


CREATE TABLE booking_table_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL,
  booking_slot_id BIGINT NOT NULL,
  venue_table_id BIGINT NOT NULL,
  seats_allocated INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_allocation_booking_slot
    FOREIGN KEY (booking_id, booking_slot_id)
    REFERENCES bookings(id, booking_slot_id),

  CONSTRAINT fk_allocation_venue_table
    FOREIGN KEY (venue_table_id)
    REFERENCES venue_tables(id),

  CONSTRAINT uq_slot_table
    UNIQUE (booking_slot_id, venue_table_id),

  CONSTRAINT uq_booking_table
    UNIQUE (booking_id, venue_table_id)
);

CREATE TABLE large_group_booking_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  request_reference VARCHAR(64) NOT NULL UNIQUE,

  venue_id BIGINT NOT NULL,

  booking_date DATE NOT NULL,

  slot_start_at TIMESTAMPTZ NOT NULL,

  party_size INT NOT NULL,

  customer_name VARCHAR(150) NOT NULL,

  customer_email VARCHAR(255) NOT NULL,

  customer_phone VARCHAR(30) NOT NULL,

  status booking_status NOT NULL DEFAULT 'pending',

  reviewed_by_user_id BIGINT,

  approved_booking_id BIGINT UNIQUE,
 
   reviewed_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_large_group_request_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT fk_large_group_request_reviewed_by
    FOREIGN KEY (reviewed_by_user_id)
    REFERENCES users(id),
 
  CONSTRAINT fk_large_group_request_approved_booking
    FOREIGN KEY (approved_booking_id)
    REFERENCES bookings(id)


);


CREATE INDEX idx_large_group_requests_status
  ON large_group_booking_requests(status);

CREATE INDEX idx_large_group_requests_booking_date
  ON large_group_booking_requests(booking_date);

CREATE INDEX idx_large_group_requests_venue
  ON large_group_booking_requests(venue_id); 

CREATE TABLE event_enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_reference VARCHAR(64) NOT NULL UNIQUE,
  customer_name VARCHAR(150) NOT NULL,
  customer_email VARCHAR(255) NOT NULL,
  customer_phone VARCHAR(30),
  event_type VARCHAR(120),
  preferred_start_at TIMESTAMPTZ,
  preferred_end_at TIMESTAMPTZ,
  expected_guest_count INT,
  message TEXT NOT NULL,
  status enquiry_status NOT NULL,
  assigned_to_user_id BIGINT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_event_enquiry_assigned_to
    FOREIGN KEY (assigned_to_user_id)
    REFERENCES users(id)
);

CREATE INDEX idx_event_enquiries_status
  ON event_enquiries(status);


-- =========================================================
-- 7. IDEMPOTENCY AND NOTIFICATIONS
-- =========================================================

CREATE TABLE idempotency_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempotency_key VARCHAR(255) NOT NULL UNIQUE,
  request_method VARCHAR(10) NOT NULL,
  request_path VARCHAR(255) NOT NULL,
  request_hash VARCHAR(128),
  status idempotency_status NOT NULL,
  response_status_code INT,
  response_body JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ
);

CREATE INDEX idx_idempotency_keys_status
  ON idempotency_keys(status);

CREATE INDEX idx_idempotency_keys_expires_at
  ON idempotency_keys(expires_at);


CREATE TABLE notification_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_reference VARCHAR(64) NOT NULL UNIQUE,
  notification_type notification_type NOT NULL,
  channel notification_channel NOT NULL,
  status notification_status NOT NULL,
  recipient_name VARCHAR(150),
  recipient_email VARCHAR(255),
  recipient_phone VARCHAR(30),
  subject VARCHAR(255),
  message_body TEXT NOT NULL,
  booking_id BIGINT,
  event_enquiry_id BIGINT,
  target_user_id BIGINT,
  attempt_count INT NOT NULL DEFAULT 0,
  last_error TEXT,
  scheduled_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_notification_booking
    FOREIGN KEY (booking_id)
    REFERENCES bookings(id),

  CONSTRAINT fk_notification_event_enquiry
    FOREIGN KEY (event_enquiry_id)
    REFERENCES event_enquiries(id),

  CONSTRAINT fk_notification_target_user
    FOREIGN KEY (target_user_id)
    REFERENCES users(id)
);

CREATE INDEX idx_notification_jobs_status
  ON notification_jobs(status);

CREATE INDEX idx_notification_jobs_booking
  ON notification_jobs(booking_id);

CREATE INDEX idx_notification_jobs_event_enquiry
  ON notification_jobs(event_enquiry_id);

CREATE INDEX idx_notification_jobs_scheduled_at
  ON notification_jobs(scheduled_at);


-- =========================================================
-- 8. ROW LEVEL SECURITY
-- =========================================================

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_access_audit_log ENABLE ROW LEVEL SECURITY;

ALTER TABLE venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE venue_hours ENABLE ROW LEVEL SECURITY;
ALTER TABLE venue_public_content ENABLE ROW LEVEL SECURITY;

ALTER TABLE menu_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

ALTER TABLE booking_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_blackouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE venue_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_slots ENABLE ROW LEVEL SECURITY;

ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_table_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_enquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE large_group_booking_requests ENABLE ROW LEVEL SECURITY;

ALTER TABLE idempotency_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_jobs ENABLE ROW LEVEL SECURITY;

COMMIT;


-- =========================================================
-- 9. MIGRATION: ADDITIONAL NOTIFICATION TYPES
-- =========================================================
-- notification_type originally had no value for a cancellation notice, a
-- large-group request being approved into a real booking, or a large-group
-- request being declined -- 'booking_confirmation' and
-- 'large_group_acknowledgement' cover the standard-booking and
-- large-group-received cases, but there was nothing correct to use for
-- these three. This adds only the missing values; it does not remove,
-- rename, or restructure anything that already existed.
--
-- ALTER TYPE ... ADD VALUE cannot run inside the same transaction as
-- other statements that use the new value, so each runs as its own
-- statement. IF NOT EXISTS makes this safe to re-run.

ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'booking_cancellation';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'large_group_confirmation';
ALTER TYPE notification_type ADD VALUE IF NOT EXISTS 'large_group_declined';


-- =========================================================
-- 10. MIGRATION: OPERATIONAL BOOKING STATUS + AUDIT COLUMNS
-- =========================================================
-- Staff need to record that a party has arrived without losing the fact
-- that they were ever "confirmed" -- 'seated' is a new, distinct state
-- (added, not repurposing 'confirmed') so operational reporting (seated
-- guests vs. remaining expected guests) can be accurate. The audit
-- columns record who/when for each terminal action; reviewed_by_user_id
-- and confirmed_at on bookings already existed and continue to be used
-- as-is for approval, so this only adds what didn't already exist:
-- seated/completed/no-show timestamps, and cancellation audit fields
-- (cancelled_by_user_id is nullable so a customer's own cancellation,
-- which has no admin user, is distinguishable from a staff cancellation).

ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'seated';

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS seated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS no_show_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS cancelled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS cancelled_by_user_id BIGINT REFERENCES users(id),
  ADD COLUMN IF NOT EXISTS cancel_reason TEXT;

ALTER TABLE large_group_booking_requests
  ADD COLUMN IF NOT EXISTS decline_reason TEXT;


-- =========================================================
-- 11. MIGRATION: SELF-MANAGED MENU DOCUMENTS
-- =========================================================
-- Lets staff replace the public menu (PDF/JPG/PNG) without a code
-- deploy. Only one document may be active per venue at a time, enforced
-- with a partial unique index rather than application logic alone, so
-- a race between two near-simultaneous publishes can't leave two rows
-- both marked active.

CREATE TABLE IF NOT EXISTS menu_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  storage_path VARCHAR(500) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  file_size_bytes BIGINT NOT NULL,
  uploaded_by_user_id BIGINT,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_menu_document_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT fk_menu_document_uploaded_by
    FOREIGN KEY (uploaded_by_user_id)
    REFERENCES users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_menu_documents_active_per_venue
  ON menu_documents(venue_id)
  WHERE is_active = TRUE;

ALTER TABLE menu_documents ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- 12. MIGRATION: PUBLIC EVENTS LISTING SUPPORT
-- =========================================================
-- The events table already carried everything the public "Upcoming
-- Events" listing needs -- starts_at/ends_at/status -- except a short
-- category label for the badge the public card design already shows
-- (previously hardcoded per-event in frontend sample data, e.g. "Live
-- Music", "Trivia"). That's the only field that didn't already exist;
-- it's nullable so existing rows, and staff who skip it, are unaffected.
-- The index supports the public listing's status + not-yet-finished
-- filter and the admin panel's upcoming/history split.

ALTER TABLE events
  ADD COLUMN IF NOT EXISTS tag VARCHAR(60);

CREATE INDEX IF NOT EXISTS idx_events_status_starts_at
  ON events(status, starts_at);


-- =========================================================
-- 13. MIGRATION: CONTACT VERIFICATION (OTP) FOR BOOKINGS
-- =========================================================
-- A customer must prove control of the email or phone they're booking
-- with before a table booking or large-group request can be created.
-- This is a new, separate table rather than an extension of anything
-- existing: notification_jobs is a durable, permanent outbound log
-- (rows are never deleted), and a one-time code must never be retained
-- anywhere in plaintext, so it can't be stored via that pipeline --
-- only a salted hash of the code is kept here. Reuses the existing
-- notification_channel enum ('email'/'sms') rather than adding a new
-- one. Booking-affecting tables (bookings, booking_slots, capacity,
-- venue_hours) are untouched by this migration.

CREATE TABLE IF NOT EXISTS verification_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  verification_reference VARCHAR(64) NOT NULL UNIQUE,
  channel notification_channel NOT NULL,
  destination VARCHAR(255) NOT NULL,
  code_hash VARCHAR(128) NOT NULL,
  attempts INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 5,
  expires_at TIMESTAMPTZ NOT NULL,
  verified_at TIMESTAMPTZ,
  consumed_at TIMESTAMPTZ,
  ip_address VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Powers both the resend-cooldown lookup (latest row for a destination)
-- and the destination-scoped rate-limit count.
CREATE INDEX IF NOT EXISTS idx_verification_requests_destination
  ON verification_requests(channel, destination, created_at DESC);

-- Powers the IP-scoped rate-limit count.
CREATE INDEX IF NOT EXISTS idx_verification_requests_ip
  ON verification_requests(ip_address, created_at DESC);

ALTER TABLE verification_requests ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- 14. MIGRATION: BOOKING SECURITY METHOD (EMAIL VERIFICATION OR DEPOSIT)
-- =========================================================
-- A standard booking is now secured one of two ways: the existing free
-- email OTP verification, or a refundable A$10 deposit. These columns
-- are additive to bookings -- capacity, booking_slots, and the existing
-- email-verification path are untouched. No payment provider is wired
-- up yet (see backend/payments/), so deposit_status can't currently
-- reach 'paid' in production; the column exists now so the schema
-- doesn't need to change again when a real provider is added.
--
-- deposit_status:
--   not_required -- default; the booking was secured by email verification
--   pending      -- a charge attempt was started but hasn't resolved yet
--   paid         -- the A$10 deposit was actually captured by a provider
--   refunded     -- an actual refund was processed (not automatic --
--                   see backend/bookings/cancellationPolicy.js; a paid
--                   deposit cancelled >=12h before the booking is left
--                   as 'paid' and shown as refund-eligible until a real
--                   refund is issued, so this value is never set as a
--                   side effect of cancelling)
--   retained     -- set automatically: cancelled <12h before start, or
--                   marked no-show -- no payment action required to
--                   "retain" money already held, so this is safe to set
--                   without a payment provider

-- Postgres has no CREATE TYPE IF NOT EXISTS, so these are wrapped to stay
-- safe to re-run like the rest of this migration.
DO $$
BEGIN
  CREATE TYPE booking_security_method AS ENUM (
    'email_verification',
    'deposit'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE deposit_status AS ENUM (
    'not_required',
    'pending',
    'paid',
    'refunded',
    'retained'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS booking_security_method booking_security_method NOT NULL DEFAULT 'email_verification',
  ADD COLUMN IF NOT EXISTS deposit_amount_cents INT,
  ADD COLUMN IF NOT EXISTS deposit_status deposit_status NOT NULL DEFAULT 'not_required',
  ADD COLUMN IF NOT EXISTS payment_provider_reference VARCHAR(255),
  ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMPTZ;

-- Postgres has no ADD CONSTRAINT IF NOT EXISTS, so this is wrapped to stay
-- safe to re-run like the ADD COLUMN statements above it.
DO $$
BEGIN
  ALTER TABLE bookings
    ADD CONSTRAINT chk_bookings_deposit_amount_positive
      CHECK (deposit_amount_cents IS NULL OR deposit_amount_cents > 0);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Selective: most bookings are deposit_status = 'not_required' and never
-- need to be found this way, so only deposit-relevant rows are indexed.
CREATE INDEX IF NOT EXISTS idx_bookings_deposit_status
  ON bookings(deposit_status)
  WHERE deposit_status <> 'not_required';


-- =========================================================
-- 15. MIGRATION: STRIPE CHECKOUT FOR THE DEPOSIT PATH
-- =========================================================
-- Deposit bookings are now real Stripe Checkout Sessions rather than the
-- always-fails placeholder from migration 14. A deposit booking exists as
-- a row with status = 'pending' (already a valid booking_status value,
-- previously unused) from the moment capacity is held, through Stripe
-- Checkout, until the webhook confirms payment -- it never becomes
-- status = 'confirmed' by any path except the webhook verifying a real
-- successful payment. hold_expires_at is how a pending row's capacity
-- hold gets released if the customer never completes payment (see
-- backend/bookings/holds.js); it's cleared once the booking is
-- confirmed, so a confirmed booking is never mistaken for an expired
-- hold. payment_provider_reference (added in migration 14, generic and
-- provider-agnostic) is superseded by the two Stripe-specific columns
-- below for anything created from here on, but is left in place rather
-- than dropped -- it's harmless, and dropping a column is not something
-- to do as a side effect of an unrelated feature.

ALTER TABLE bookings
  ADD COLUMN IF NOT EXISTS stripe_checkout_session_id VARCHAR(255),
  ADD COLUMN IF NOT EXISTS stripe_payment_intent_id VARCHAR(255),
  ADD COLUMN IF NOT EXISTS hold_expires_at TIMESTAMPTZ;

DO $$
BEGIN
  ALTER TABLE bookings
    ADD CONSTRAINT uq_bookings_stripe_checkout_session_id
      UNIQUE (stripe_checkout_session_id);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- Powers the sweep that releases an expired hold's capacity, and the
-- webhook's lookup by session id.
CREATE INDEX IF NOT EXISTS idx_bookings_pending_hold_expiry
  ON bookings(booking_slot_id, hold_expires_at)
  WHERE status = 'pending';


-- =========================================================
-- 16. MIGRATION: ADMIN NOTIFICATION CENTRE
-- =========================================================
-- In-app notifications for staff (a bell/dropdown on the admin dashboard),
-- entirely separate from notification_jobs above -- that table is an
-- outbound delivery log to CUSTOMERS (email/SMS via a provider); this one
-- is short-lived, in-app state read by an admin's own browser. Sharing one
-- table across several source event types (bookings, large-group
-- requests, event enquiries, and future system alerts) with a plain
-- entity_type/entity_id pair rather than several nullable FK columns
-- (or per-type notification tables) keeps one new row shape regardless of
-- what triggered it; no FK constraint is attached to entity_id on purpose,
-- since a single column can't reference more than one table, and a
-- notification also intentionally outlives whatever it points to (e.g. a
-- booking cancelled long ago).
--
-- `type` is a plain VARCHAR rather than an enum: unlike the customer-facing
-- notification_type above, new admin notification types are expected to be
-- added often (deposit received/failed/refunded, verification issues,
-- system alerts, ...) and a VARCHAR needs no ALTER TYPE migration to grow.
-- Known values today: 'new_booking', 'booking_cancelled',
-- 'large_group_request', 'event_enquiry'.
--
-- The partial unique index below is what makes notification creation safe
-- to call more than once for the same underlying event (an idempotency-key
-- retry, or any other accidental double-call): a second insert for the
-- same (type, entity_type, entity_id) is silently ignored rather than
-- producing a duplicate row. It's partial (entity_id IS NOT NULL) so a
-- future entity-less system alert is never blocked from repeating.

CREATE TABLE IF NOT EXISTS admin_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(60) NOT NULL,
  title VARCHAR(200) NOT NULL,
  message TEXT NOT NULL,
  entity_type VARCHAR(30),
  entity_id BIGINT,
  metadata JSONB,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_admin_notifications_dedupe
  ON admin_notifications(type, entity_type, entity_id)
  WHERE entity_id IS NOT NULL;

-- Powers "newest first" listing.
CREATE INDEX IF NOT EXISTS idx_admin_notifications_created_at
  ON admin_notifications(created_at DESC);

-- Selective: most rows are read soon after creation, so only the unread
-- ones (which is what the bell's badge count and dropdown care about) are
-- indexed.
CREATE INDEX IF NOT EXISTS idx_admin_notifications_unread
  ON admin_notifications(is_read)
  WHERE is_read = FALSE;

ALTER TABLE admin_notifications ENABLE ROW LEVEL SECURITY;


-- =========================================================
-- 17. MIGRATION: MULTI-PAGE MENU (MENU VERSIONS + MENU PAGES)
-- =========================================================
-- menu_documents (migration 11) stored one row per uploaded file with a
-- single is_active flag, enforced to exactly one active row per venue by
-- uq_menu_documents_active_per_venue -- so publishing a new file could only
-- ever mean *replacing* the whole menu, never adding a page alongside it.
-- That table is left in place untouched (harmless, and dropping it is not
-- something to do as a side effect of an unrelated feature); it's simply
-- superseded by the two tables below and no longer written to.
--
-- menu_versions is what "the current published menu" now means, and
-- menu_pages is its ordered contents -- the same venue_id +
-- one-active-row-per-venue shape as menu_documents, just generalized from
-- "one document" to "one version made of N ordered pages". A version's
-- pages share its lifecycle (ON DELETE CASCADE) since a page never makes
-- sense detached from the version listing it.
--
-- Publishing stays immediate, matching every other admin action in this
-- app (approve/decline/status-change all take effect the moment they're
-- called) -- there is no admin-facing draft/staging concept anywhere else
-- to extend, and introducing one here alone would mean the admin menu
-- screen and the public site disagreeing about what's live until a
-- separate publish step, which nothing else in this codebase does. So
-- add/replace/delete/reorder all mutate the one status = 'published'
-- version's pages directly and immediately, exactly like uploading a new
-- menu_documents row used to. Old menu_documents rows (both the previously
-- active one and its prior history) are migrated below into this shape
-- without deleting anything, preserved as their own one-page
-- status = 'archived' versions -- real history, not synthesized.
CREATE TYPE menu_version_status AS ENUM (
  'published',
  'archived'
);

CREATE TABLE IF NOT EXISTS menu_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  status menu_version_status NOT NULL DEFAULT 'published',
  published_at TIMESTAMPTZ,
  uploaded_by_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_menu_version_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT fk_menu_version_uploaded_by
    FOREIGN KEY (uploaded_by_user_id)
    REFERENCES users(id)
);

-- Same shape as uq_menu_documents_active_per_venue above -- exactly one
-- live published version per venue at a time.
CREATE UNIQUE INDEX IF NOT EXISTS uq_menu_versions_published_per_venue
  ON menu_versions(venue_id)
  WHERE status = 'published';

CREATE TABLE IF NOT EXISTS menu_pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_version_id BIGINT NOT NULL,
  sort_order INT NOT NULL,
  title VARCHAR(120),
  file_name VARCHAR(255) NOT NULL,
  storage_path VARCHAR(500) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  file_size_bytes BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_menu_page_version
    FOREIGN KEY (menu_version_id)
    REFERENCES menu_versions(id)
    ON DELETE CASCADE,

  CONSTRAINT uq_menu_page_version_sort_order
    UNIQUE (menu_version_id, sort_order)
);

-- Powers both "load this version's pages in order" (admin panel and the
-- public viewer) and the reorder/delete resequencing queries.
CREATE INDEX IF NOT EXISTS idx_menu_pages_version_sort
  ON menu_pages(menu_version_id, sort_order);

ALTER TABLE menu_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_pages ENABLE ROW LEVEL SECURITY;

-- One-off data migration: copies every existing menu_documents row into
-- the new shape, guarded so it only ever runs once (even if this file is
-- re-applied) by checking menu_versions is still empty. The previously
-- active document becomes page 1 of a new published version; every other
-- (already-inactive) document becomes its own one-page archived version,
-- preserving real upload history instead of collapsing or discarding it.
-- No menu_documents row is modified or deleted by this.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM menu_versions) THEN

    INSERT INTO menu_versions (venue_id, status, published_at, uploaded_by_user_id, created_at, updated_at)
    SELECT venue_id, 'published', created_at, uploaded_by_user_id, created_at, updated_at
    FROM menu_documents
    WHERE is_active = TRUE;

    INSERT INTO menu_pages (menu_version_id, sort_order, file_name, storage_path, mime_type, file_size_bytes, created_at, updated_at)
    SELECT mv.id, 1, md.file_name, md.storage_path, md.mime_type, md.file_size_bytes, md.created_at, md.updated_at
    FROM menu_documents md
    JOIN menu_versions mv
      ON mv.venue_id = md.venue_id AND mv.status = 'published'
    WHERE md.is_active = TRUE;

    INSERT INTO menu_versions (venue_id, status, published_at, uploaded_by_user_id, created_at, updated_at)
    SELECT venue_id, 'archived', NULL, uploaded_by_user_id, created_at, updated_at
    FROM menu_documents
    WHERE is_active = FALSE;

    -- Matches each archived version back to its source document by
    -- identity (venue_id, created_at, uploaded_by_user_id) -- safe here
    -- because this whole block runs exactly once, immediately after the
    -- INSERT above created them in the same shape from the same rows.
    INSERT INTO menu_pages (menu_version_id, sort_order, file_name, storage_path, mime_type, file_size_bytes, created_at, updated_at)
    SELECT mv.id, 1, md.file_name, md.storage_path, md.mime_type, md.file_size_bytes, md.created_at, md.updated_at
    FROM menu_documents md
    JOIN menu_versions mv
      ON mv.venue_id = md.venue_id
     AND mv.status = 'archived'
     AND mv.created_at = md.created_at
     AND (mv.uploaded_by_user_id = md.uploaded_by_user_id
          OR (mv.uploaded_by_user_id IS NULL AND md.uploaded_by_user_id IS NULL))
    WHERE md.is_active = FALSE;

  END IF;
END $$;
