-- =========================================================
-- Bar 185 PostgreSQL Database Schema
-- =========================================================

BEGIN;

-- =========================================================
-- 1. ENUM TYPES
-- =========================================================

CREATE TYPE user_account_status AS ENUM (
  'active',
  'disabled',
  'removed'
);

CREATE TYPE auth_provider_type AS ENUM (
  'google',
  'mobile_otp'
);

CREATE TYPE staff_account_status AS ENUM (
  'pending',
  'approved',
  'disabled',
  'removed'
);

CREATE TYPE staff_access_action_type AS ENUM (
  'account_created',
  'account_approved',
  'account_disabled',
  'account_removed',
  'account_restored',
  'role_assigned',
  'role_removed'
);

CREATE TYPE menu_item_status AS ENUM (
  'draft',
  'active',
  'unavailable',
  'archived'
);

CREATE TYPE event_status AS ENUM (
  'draft',
  'published',
  'cancelled',
  'completed',
  'archived'
);

CREATE TYPE venue_table_status AS ENUM (
  'active',
  'unavailable',
  'retired'
);

CREATE TYPE booking_type AS ENUM (
  'standard',
  'large_group'
);

CREATE TYPE booking_status AS ENUM (
  'pending',
  'confirmed',
  'declined',
  'cancelled',
  'completed',
  'no_show'
);

CREATE TYPE enquiry_status AS ENUM (
  'new',
  'acknowledged',
  'in_review',
  'contacted',
  'quoted',
  'closed',
  'declined'
);

CREATE TYPE notification_type AS ENUM (
  'booking_confirmation',
  'large_group_acknowledgement',
  'large_group_staff_alert',
  'event_enquiry_acknowledgement',
  'event_enquiry_staff_alert',
  'staff_access_alert'
);

CREATE TYPE notification_channel AS ENUM (
  'email',
  'sms'
);

CREATE TYPE notification_status AS ENUM (
  'pending',
  'queued',
  'sending',
  'sent',
  'failed',
  'cancelled'
);

CREATE TYPE idempotency_status AS ENUM (
  'processing',
  'completed',
  'failed'
);


-- =========================================================
-- 2. IDENTITY AND ACCESS
-- =========================================================

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  display_name VARCHAR(120) NOT NULL,
  email VARCHAR(255) UNIQUE,
  phone_e164 VARCHAR(30) UNIQUE,
  status user_account_status NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE auth_identities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  provider_type auth_provider_type NOT NULL,
  provider_subject VARCHAR(255) NOT NULL,
  verified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_auth_identity_user
    FOREIGN KEY (user_id)
    REFERENCES users(id),

  CONSTRAINT uq_auth_provider_subject
    UNIQUE (provider_type, provider_subject),

  CONSTRAINT uq_user_provider
    UNIQUE (user_id, provider_type)
);


CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_code VARCHAR(50) NOT NULL UNIQUE,
  role_name VARCHAR(100) NOT NULL,
  description TEXT
);


CREATE TABLE user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  assigned_by_user_id BIGINT,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_user_role_user
    FOREIGN KEY (user_id)
    REFERENCES users(id),

  CONSTRAINT fk_user_role_role
    FOREIGN KEY (role_id)
    REFERENCES roles(id),

  CONSTRAINT fk_user_role_assigned_by
    FOREIGN KEY (assigned_by_user_id)
    REFERENCES users(id),

  CONSTRAINT uq_user_role
    UNIQUE (user_id, role_id)
);


CREATE TABLE staff_accounts (
  user_id BIGINT PRIMARY KEY,
  staff_reference VARCHAR(64) NOT NULL UNIQUE,
  status staff_account_status NOT NULL,
  approved_by_user_id BIGINT,
  approved_at TIMESTAMPTZ,
  disabled_at TIMESTAMPTZ,
  removed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_staff_account_user
    FOREIGN KEY (user_id)
    REFERENCES users(id),

  CONSTRAINT fk_staff_account_approved_by
    FOREIGN KEY (approved_by_user_id)
    REFERENCES users(id)
);


CREATE TABLE staff_access_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  target_user_id BIGINT NOT NULL,
  performed_by_user_id BIGINT,
  action_type staff_access_action_type NOT NULL,
  role_id BIGINT,
  previous_staff_status staff_account_status,
  new_staff_status staff_account_status,
  request_id VARCHAR(64),
  reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_staff_audit_target_user
    FOREIGN KEY (target_user_id)
    REFERENCES users(id),

  CONSTRAINT fk_staff_audit_performed_by
    FOREIGN KEY (performed_by_user_id)
    REFERENCES users(id),

  CONSTRAINT fk_staff_audit_role
    FOREIGN KEY (role_id)
    REFERENCES roles(id)
);

CREATE INDEX idx_staff_audit_request_id
  ON staff_access_audit_log(request_id);

CREATE INDEX idx_staff_audit_target_user
  ON staff_access_audit_log(target_user_id);

CREATE INDEX idx_staff_audit_performed_by
  ON staff_access_audit_log(performed_by_user_id);

CREATE INDEX idx_staff_audit_created_at
  ON staff_access_audit_log(created_at);


-- =========================================================
-- 3. VENUE CONFIGURATION
-- =========================================================

CREATE TABLE venues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_reference VARCHAR(64) NOT NULL UNIQUE,
  venue_name VARCHAR(150) NOT NULL,
  address_line1 VARCHAR(255) NOT NULL,
  suburb VARCHAR(120) NOT NULL,
  state VARCHAR(80) NOT NULL,
  postcode VARCHAR(20) NOT NULL,
  country VARCHAR(100) NOT NULL,
  public_phone VARCHAR(30),
  public_email VARCHAR(255),
  timezone VARCHAR(100) NOT NULL,
  is_active BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE venue_hours (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  day_of_week INT NOT NULL,
  opens_at TIME,
  closes_at TIME,
  is_closed BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_venue_hours_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT uq_venue_hours_day
    UNIQUE (venue_id, day_of_week)
);


CREATE TABLE venue_public_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  content_key VARCHAR(100) NOT NULL,
  content_value TEXT NOT NULL,
  sort_order INT NOT NULL,
  is_active BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_venue_public_content_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT uq_venue_content_key
    UNIQUE (venue_id, content_key)
);


-- =========================================================
-- 4. MENU AND EVENTS
-- =========================================================

CREATE TABLE menu_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_reference VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(120) NOT NULL,
  slug VARCHAR(150) NOT NULL UNIQUE,
  description TEXT,
  sort_order INT NOT NULL,
  is_active BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


CREATE TABLE menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  menu_item_reference VARCHAR(64) NOT NULL UNIQUE,
  category_id BIGINT NOT NULL,
  name VARCHAR(150) NOT NULL,
  slug VARCHAR(180) NOT NULL UNIQUE,
  sku VARCHAR(80) UNIQUE,
  description TEXT,
  price NUMERIC(10,2) NOT NULL,
  status menu_item_status NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_menu_item_category
    FOREIGN KEY (category_id)
    REFERENCES menu_categories(id)
);


CREATE TABLE events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_reference VARCHAR(64) NOT NULL UNIQUE,
  title VARCHAR(180) NOT NULL,
  slug VARCHAR(200) NOT NULL UNIQUE,
  description TEXT,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ,
  status event_status NOT NULL,
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_event_created_by
    FOREIGN KEY (created_by_user_id)
    REFERENCES users(id)
);


-- =========================================================
-- 5. BOOKING CONFIGURATION
-- =========================================================

CREATE TABLE booking_rules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  minimum_party_size INT NOT NULL,
  maximum_standard_party_size INT NOT NULL,
  large_group_threshold INT NOT NULL,
  booking_window_days INT NOT NULL,
  slot_interval_minutes INT NOT NULL,
  standard_booking_duration_minutes INT NOT NULL,
  public_instructions TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_booking_rules_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT uq_booking_rules_venue
    UNIQUE (venue_id)
);


CREATE TABLE booking_blackouts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  reason VARCHAR(255),
  blocks_public_bookings BOOLEAN NOT NULL,
  created_by_user_id BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_booking_blackout_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT fk_booking_blackout_created_by
    FOREIGN KEY (created_by_user_id)
    REFERENCES users(id)
);

CREATE INDEX idx_booking_blackouts_venue
  ON booking_blackouts(venue_id);

CREATE INDEX idx_booking_blackouts_starts_at
  ON booking_blackouts(starts_at);

CREATE INDEX idx_booking_blackouts_ends_at
  ON booking_blackouts(ends_at);


CREATE TABLE venue_tables (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  table_code VARCHAR(50) NOT NULL,
  table_name VARCHAR(100) NOT NULL,
  capacity INT NOT NULL,
  status venue_table_status NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_venue_table_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT uq_venue_table_code
    UNIQUE (venue_id, table_code)
);


CREATE TABLE booking_slots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id BIGINT NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  total_capacity INT NOT NULL,
  reserved_capacity INT NOT NULL,
  version_number INT NOT NULL,
  is_open BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_booking_slot_venue
    FOREIGN KEY (venue_id)
    REFERENCES venues(id),

  CONSTRAINT uq_booking_slot_time
    UNIQUE (venue_id, starts_at, ends_at)
);


-- =========================================================
-- 6. BOOKINGS AND EVENT ENQUIRIES
-- =========================================================

CREATE TABLE bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_reference VARCHAR(64) NOT NULL UNIQUE,
  booking_slot_id BIGINT NOT NULL,
  booking_type booking_type NOT NULL,
  status booking_status NOT NULL,
  party_size INT NOT NULL,
  customer_name VARCHAR(150) NOT NULL,
  customer_email VARCHAR(255) NOT NULL,
  customer_phone VARCHAR(30),
  special_requests TEXT,
  reviewed_by_user_id BIGINT,
  confirmed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_booking_slot
    FOREIGN KEY (booking_slot_id)
    REFERENCES booking_slots(id),

  CONSTRAINT fk_booking_reviewed_by
    FOREIGN KEY (reviewed_by_user_id)
    REFERENCES users(id),

  CONSTRAINT uq_booking_id_slot
    UNIQUE (id, booking_slot_id)
);

CREATE INDEX idx_bookings_slot
  ON bookings(booking_slot_id);

CREATE INDEX idx_bookings_status
  ON bookings(status);


CREATE TABLE booking_table_allocations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_id BIGINT NOT NULL,
  booking_slot_id BIGINT NOT NULL,
  venue_table_id BIGINT NOT NULL,
  seats_allocated INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_allocation_booking_slot
    FOREIGN KEY (booking_id, booking_slot_id)
    REFERENCES bookings(id, booking_slot_id),

  CONSTRAINT fk_allocation_venue_table
    FOREIGN KEY (venue_table_id)
    REFERENCES venue_tables(id),

  CONSTRAINT uq_slot_table
    UNIQUE (booking_slot_id, venue_table_id),

  CONSTRAINT uq_booking_table
    UNIQUE (booking_id, venue_table_id)
);


CREATE TABLE event_enquiries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enquiry_reference VARCHAR(64) NOT NULL UNIQUE,
  customer_name VARCHAR(150) NOT NULL,
  customer_email VARCHAR(255) NOT NULL,
  customer_phone VARCHAR(30),
  event_type VARCHAR(120),
  preferred_start_at TIMESTAMPTZ,
  preferred_end_at TIMESTAMPTZ,
  expected_guest_count INT,
  message TEXT NOT NULL,
  status enquiry_status NOT NULL,
  assigned_to_user_id BIGINT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_event_enquiry_assigned_to
    FOREIGN KEY (assigned_to_user_id)
    REFERENCES users(id)
);

CREATE INDEX idx_event_enquiries_status
  ON event_enquiries(status);


-- =========================================================
-- 7. IDEMPOTENCY AND NOTIFICATIONS
-- =========================================================

CREATE TABLE idempotency_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  idempotency_key VARCHAR(255) NOT NULL UNIQUE,
  request_method VARCHAR(10) NOT NULL,
  request_path VARCHAR(255) NOT NULL,
  request_hash VARCHAR(128),
  status idempotency_status NOT NULL,
  response_status_code INT,
  response_body JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ
);

CREATE INDEX idx_idempotency_keys_status
  ON idempotency_keys(status);

CREATE INDEX idx_idempotency_keys_expires_at
  ON idempotency_keys(expires_at);


CREATE TABLE notification_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  notification_reference VARCHAR(64) NOT NULL UNIQUE,
  notification_type notification_type NOT NULL,
  channel notification_channel NOT NULL,
  status notification_status NOT NULL,
  recipient_name VARCHAR(150),
  recipient_email VARCHAR(255),
  recipient_phone VARCHAR(30),
  subject VARCHAR(255),
  message_body TEXT NOT NULL,
  booking_id BIGINT,
  event_enquiry_id BIGINT,
  target_user_id BIGINT,
  attempt_count INT NOT NULL DEFAULT 0,
  last_error TEXT,
  scheduled_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_notification_booking
    FOREIGN KEY (booking_id)
    REFERENCES bookings(id),

  CONSTRAINT fk_notification_event_enquiry
    FOREIGN KEY (event_enquiry_id)
    REFERENCES event_enquiries(id),

  CONSTRAINT fk_notification_target_user
    FOREIGN KEY (target_user_id)
    REFERENCES users(id)
);

CREATE INDEX idx_notification_jobs_status
  ON notification_jobs(status);

CREATE INDEX idx_notification_jobs_booking
  ON notification_jobs(booking_id);

CREATE INDEX idx_notification_jobs_event_enquiry
  ON notification_jobs(event_enquiry_id);

CREATE INDEX idx_notification_jobs_scheduled_at
  ON notification_jobs(scheduled_at);


-- =========================================================
-- 8. ROW LEVEL SECURITY
-- =========================================================

ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE auth_identities ENABLE ROW LEVEL SECURITY;
ALTER TABLE roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_access_audit_log ENABLE ROW LEVEL SECURITY;

ALTER TABLE venues ENABLE ROW LEVEL SECURITY;
ALTER TABLE venue_hours ENABLE ROW LEVEL SECURITY;
ALTER TABLE venue_public_content ENABLE ROW LEVEL SECURITY;

ALTER TABLE menu_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;

ALTER TABLE booking_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_blackouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE venue_tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_slots ENABLE ROW LEVEL SECURITY;

ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_table_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_enquiries ENABLE ROW LEVEL SECURITY;

ALTER TABLE idempotency_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE notification_jobs ENABLE ROW LEVEL SECURITY;

COMMIT;
